#filename:.travis.yml
dist: xenial
sudo: false
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
  - PACKAGE=vlmcsd
  - USER=dwfreed
  - REPO=openwrt-vlmcsd
  - OSVER=OpenWrt
  matrix:
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/apm821xx/nand/openwrt-sdk-18.06.2-apm821xx-nand_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/ar71xx/generic/openwrt-sdk-18.06.2-ar71xx-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/armvirt/64/openwrt-sdk-18.06.2-armvirt-64_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/bcm53xx/generic/openwrt-sdk-18.06.2-bcm53xx_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/brcm2708/bcm2708/openwrt-sdk-18.06.2-brcm2708-bcm2708_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/brcm2708/bcm2709/openwrt-sdk-18.06.2-brcm2708-bcm2709_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/brcm47xx/generic/openwrt-sdk-18.06.2-brcm47xx-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/brcm47xx/mips74k/openwrt-sdk-18.06.2-brcm47xx-mips74k_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/brcm63xx/generic/openwrt-sdk-18.06.2-brcm63xx-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/ipq806x/generic/openwrt-sdk-18.06.2-ipq806x_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/kirkwood/generic/openwrt-sdk-18.06.2-kirkwood_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/mpc85xx/generic/openwrt-sdk-18.06.2-mpc85xx-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/mvebu/cortexa53/openwrt-sdk-18.06.2-mvebu-cortexa53_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/mvebu/cortexa72/openwrt-sdk-18.06.2-mvebu-cortexa72_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/mvebu/cortexa9/openwrt-sdk-18.06.2-mvebu-cortexa9_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/octeon/generic/openwrt-sdk-18.06.2-octeon_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/ramips/mt7620/openwrt-sdk-18.06.2-ramips-mt7620_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/x86/64/openwrt-sdk-18.06.2-x86-64_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  - SDK_URL=https://downloads.openwrt.org/releases/18.06.2/targets/x86/generic/openwrt-sdk-18.06.2-x86-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.4.1-1_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- tar xf $FILE
- if [ "$OSVER" = "OpenWrt" ]; then SDK_DIR="openwrt-sdk-*"; elif [ "$OSVER" = "LEDE" ]; then SDK_DIR="lede-sdk-*"; fi
- cd $TRAVIS_BUILD_DIR/sdk/$SDK_DIR
- "echo 'untrusted comment: usign key of Doug Freed' > key-build"
- echo "$SIGNING_KEY" >> key-build
- mkdir package/vlmcsd
- ln -s $TRAVIS_BUILD_DIR/Makefile package/vlmcsd/
- ln -s $TRAVIS_BUILD_DIR/files package/vlmcsd/
script:
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/$SDK_DIR
- export SDK_DIR=$(basename `pwd`)
- export PATH=$TRAVIS_BUILD_DIR/sdk/$SDK_DIR/staging_dir/host/bin:$PATH
- pushd staging_dir/toolchain-*
- TOOLCHAIN_DIR=$(basename `pwd`)
- export PATH=$TRAVIS_BUILD_DIR/sdk/$SDK_DIR/staging_dir/$TOOLCHAIN_DIR/bin:$PATH
- popd
- ./scripts/feeds update packages >/dev/null
- make defconfig
- make package/vlmcsd/compile V=s
- make -j1 V=s package/index
- cd $TRAVIS_BUILD_DIR/
after_success: "$TRAVIS_BUILD_DIR/deploy.sh"
